# Generated by Django 6.0.7 on 2026-09-12 00:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pais')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('x_url', models.URLField(blank=True, null=True, verbose_name='X (Twitter)')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='Ultima Actividad')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Términos Aceptados')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Términos Aceptados con fecha')),
                ('email_notifications_enabled', models.BooleanField(default=True, verbose_name='Notificaciones por Email Habilitadas')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('legal_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Legal (Razón Social)')),
                ('tax_id', models.CharField(max_length=50, unique=True, verbose_name='Tax ID (RUT/NIT/CUIT)')),
                ('corporate_email', models.EmailField(max_length=254, verbose_name='Correo Corporativo')),
                ('billing_email', models.EmailField(help_text='Correo Administración', max_length=254, verbose_name='Billing email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('logo', models.ImageField(default='companies/default_logo.jpg', upload_to='companies/logos/', verbose_name='Logo Empresa')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si la empresa ha sido verificada manualmente por un administrador del sistema.', verbose_name='Verified company')),
                ('plan', models.CharField(choices=[('basic', 'Básico'), ('professional', 'Profesional'), ('enterprise', 'Corporativo')], default='basic', max_length=20, verbose_name='Plan de Suscripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta empresa tiene permiso para utilizar el sistema.', verbose_name='Active')),
                ('subscription_start', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio de la Suscripción')),
                ('subscription_end', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin de la Suscripción')),
                ('subdomain', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Subdominio')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Información Adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Companía',
                'verbose_name_plural': 'Companias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Marca')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='stockv.company')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('warehouse_staff', 'Personal de Depósito'), ('sales', 'Ventas')], default='warehouse_staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='stockv.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Proveedor')),
                ('tax_id', models.CharField(blank=True, help_text='Identificación Tributaria del Proveedor', max_length=50, null=True, verbose_name='RUT / NIT / CUIT')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('state_province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento / Provincia')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código Postal')),
                ('provider_type', models.CharField(choices=[('LOCAL', 'Local'), ('NATIONAL', 'Nacional'), ('INTERNATIONAL', 'Internacional'), ('DISTRIBUTOR', 'Distribuidor'), ('MANUFACTURER', 'Fabricante'), ('WHOLESALER', 'Mayorista')], default='LOCAL', max_length=50, verbose_name='Tipo de Proveedor')),
                ('payment_terms', models.CharField(blank=True, help_text='Ej: 30 días, 60 días, contado, etc.', max_length=100, null=True, verbose_name='Condiciones de Pago')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo de crédito otorgado', max_digits=12, null=True, verbose_name='Límite de Crédito')),
                ('currency', models.CharField(choices=[('UYU', 'Peso Uruguayo'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('ARS', 'Peso Argentino'), ('MXN', 'Peso Mexicano'), ('COP', 'Peso Colombiano'), ('CLP', 'Peso Chileno'), ('PEN', 'Sol Peruano')], default='USD', max_length=3, verbose_name='Moneda')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Calificación del proveedor del 1 al 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='Proveedor Preferente')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si el proveedor ha sido verificado por la empresa', verbose_name='Proveedor Verificado')),
                ('main_products', models.TextField(blank=True, help_text='Principales productos o servicios que ofrece', null=True, verbose_name='Productos/Servicios Principales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_purchase', models.DateTimeField(blank=True, null=True, verbose_name='Última Compra')),
                ('account_manager', models.ForeignKey(blank=True, help_text='Persona responsable de la relación con este proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_providers', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo de Cuenta')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='stockv.company')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Unit name')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Abbreviation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='stockv.company')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU / Código Interno')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barras / EAN')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(default='products/default_product.jpg', upload_to='products/', verbose_name='Foto del Producto')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio de Costo')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio Ventas')),
                ('min_stock_level', models.PositiveIntegerField(default=0, help_text='Cantidad mínima que debe haber en inventario antes de reabastecer', verbose_name='Nivel Mínimo de Stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stockv.brand', verbose_name='Marca')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stockv.company', verbose_name='Companía')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stockv.provider', verbose_name='Proveedor')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='stockv.unitofmeasure', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Depósito')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Depósito Código Interno')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state_province', models.CharField(max_length=100, verbose_name='Departamento / Provincia')),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código Postal')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Capacidad de Almacenamiento en Unidades o Volumen', null=True, verbose_name='Capacity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='stockv.company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Gerente')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Ingreso'), ('out', 'Egreso'), ('transfer', 'Transferencia entre Depósitos'), ('adjustment', 'Ajuste Manual')], max_length=15)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='stockv.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockv.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockv.warehouse')),
            ],
            options={
                'verbose_name': 'Stock movement',
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='providers', to='stockv.warehouse', verbose_name='Depósitos Asociados'),
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity in stock')),
                ('aisle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pasillo')),
                ('shelf', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estantería')),
                ('bin_rack', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contenedor / Rack')),
                ('last_inventory_check', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo Inventario Manual')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='stockv.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='stockv.warehouse')),
            ],
            options={
                'verbose_name': 'Stock en Depósito',
                'verbose_name_plural': 'Stocks en Depósito',
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockv.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='stockv.warehouse')),
                ('origin_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='stockv.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockv.product')),
            ],
            options={
                'verbose_name': 'Transferencia entre Depósitos',
                'verbose_name_plural': 'Transferencias entre Depósitos',
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, verbose_name='Número de Factura')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(verbose_name='Inicio de la Garantía')),
                ('end_date', models.DateField(verbose_name='Fecha de Caducidad de la Garantía')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='stockv.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockv.product')),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.TextField(verbose_name='Motivos de la Devolución')),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('damaged', 'Dañado'), ('opened', 'Caja Abierta')], default='opened', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockv.company')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockv.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockv.warehouse')),
                ('warranty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='stockv.warranty', verbose_name='Garantía Asociada')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='stockv_user_email_bf7774_idx'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_name_brand'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='unique_user_company_membership'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_name_uom'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'brand'], name='stockv_prod_company_55a4d0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'barcode'], name='stockv_prod_company_e37e05_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'sku'), name='unique_company_sku_name'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_name_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_code_warehouse'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['company', 'is_active'], name='stockv_prov_company_3909e4_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['company', 'is_preferred'], name='stockv_prov_company_6b0dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['company', 'rating'], name='stockv_prov_company_27f711_idx'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_provider_name'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_provider_code'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id__isnull', False)), fields=('company', 'tax_id'), name='unique_company_provider_tax_id'),
        ),
        migrations.AddConstraint(
            model_name='warehousestock',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='unique_product_warehouse_warehousestock'),
        ),
    ]
